"""Remove only local data products generated by this repository."""

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
for relative in ("data", "spark-warehouse", "metastore_db"):
    target = (ROOT / relative).resolve()
    if target.parent == ROOT and target.exists():
        if target.is_dir():
            shutil.rmtree(target)
        else:
            target.unlink()

derby_log = ROOT / "derby.log"
if derby_log.exists():
    derby_log.unlink()
